### ISSUE TITLE
Please update knockout to 3.5.1

### ISSUE THREAD

**Issue by trohr** [webjars/knockout#10]
Hello, please update knockout to 3.5.1.

https://github.com/knockout/knockout/releases/tag/v3.5.1

Reasons:
1. There are some bugfixes in this version.
2. your webjar package seems to be the most correct one as the others contain multiple other files that are really not necessary (your version rocks ;))

Thank you.
Tomas Rohrbacher

**Comment by jamesward** [comment]
This will be released shortly.
